name: Build Native

on: [workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Configure win-x64
      run: cmake . -G "Visual Studio 17 2022" -A x64 -Bbuild_win_64 -DCMAKE_BUILD_TYPE:String=Distribution
    - name: Build win-x64
      run: cmake --build build_win_64 --config Distribution

    - name: Configure win-arm64
      run: cmake . -G "Visual Studio 17 2022" -A ARM64 -Bbuild_win_arm64 -DCMAKE_BUILD_TYPE:String=Distribution
    - name: Build win-arm64
      run: cmake --build build_win_arm64 --config Distribution
    - name: Package Windows
      run: |
        mkdir bin/win-x64/native
        mkdir bin/win-arm64/native
        mv build_win_64\bin\Distribution\joltc.dll bin/win-x64/native
        mv build_win_arm64\bin\Distribution\joltc.dll bin/win-arm64/native
    - uses: actions/upload-artifact@v3
      with:
        name: libs_windows
        path: bin

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install libzstd-dev ninja-build
    - name: Configure linux-x64
      run: cmake S . -Bbuild_linux_64 -G Ninja -DCMAKE_BUILD_TYPE=Distribution
    - name: Build linux-x64
      run: cmake --build build_linux_64 --config Distribution --verbose --parallel

    # Linux artifact 
    - name: package_linux
      run: |
        mkdir -p bin/linux-x64/native
        mv build_linux_64/lib/libjoltc bin/linux-x64/native/libjoltc
    - uses: actions/upload-artifact@v3
      with:
        name: libs_linux
        path: bin

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup dependencies
      run: |
        brew install \
          ninja \
          llvm

    - name: Configure osx-universal
      run: cmake -S . -Bbuild_osx -G Ninja -DCMAKE_BUILD_TYPE=Distribution
    - name: Build osx-universal
      run: cmake --build build_osx --config Distribution --verbose --parallel

    # macOS artifacts
    - name: package_osx
      run: |
        mkdir -p bin/osx-universal/native
        mv build_osx/lib/libjoltc.dylib bin/osx-universal/native/libjoltc.dylib
    - uses: actions/upload-artifact@v3
      with:
        name: libs_osx
        path: bin

  combine:
    name: combine artifacts
    runs-on: ubuntu-20.04
    needs: [windows, linux, macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts
      - name: combine
        run: |
          mkdir native_libs
          cp -r artifacts/libs_windows/* native_libs
          cp -r artifacts/libs_linux/* native_libs
          cp -r artifacts/libs_osx/* native_libs
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z native_libs.7z ./native_libs/
      - uses: AButler/upload-release-assets@v2.0
        if: github.event_name == 'release' && github.event.action == 'created'
        with:
          files: native_libs.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: 'Build Artifacts'
          path: native_libs.7z
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            libs_windows
            libs_linux
            libs_osx
