name: Build Native

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'src/joltc/**'
      - .github/workflows/build_native.yml
  pull_request:
    paths:
      - 'src/joltc/**'
      - .github/workflows/build_native.yml

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.28
      
    - name: Configure win-x64
      run: cmake -S "." -B "build_win_64" -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE:String=Distribution
    - name: Build win-x64
      run: cmake --build build_win_64 --config Distribution

    - name: Configure win-x64 double
      run: cmake -S "." -B "build_win_64_double" -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE:String=Distribution -DDOUBLE_PRECISION=ON
    - name: Build win-x64 double
      run: cmake --build build_win_64_double --config Distribution      

    - name: Configure win-arm64
      run: cmake -S "." -B "build_win_arm64" -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_BUILD_TYPE:String=Distribution
    - name: Build win-arm64
      run: cmake --build build_win_arm64 --config Distribution

    - name: Configure win-arm64 double
      run: cmake -S "." -B "build_win_arm64_double" -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_BUILD_TYPE:String=Distribution -DDOUBLE_PRECISION=ON
    - name: Build win-arm64 double
      run: cmake --build build_win_arm64_double --config Distribution

    - name: Package Windows
      run: |
        mkdir bin/win-x64/native
        mkdir bin/win-arm64/native
        mv build_win_64\bin\Distribution\joltc.dll bin/win-x64/native
        mv build_win_64_double\bin\Distribution\joltc_double.dll bin/win-x64/native
        mv build_win_arm64\bin\Distribution\joltc.dll bin/win-arm64/native
        mv build_win_arm64_double\bin\Distribution\joltc_double.dll bin/win-arm64/native
    - uses: actions/upload-artifact@v3
      with:
        name: libs_windows
        path: bin

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.28

    - name: Configure linux-x64
      run: cmake -S "." -B "build_linux_64" -G Ninja -DCMAKE_BUILD_TYPE=Distribution
    - name: Build linux-x64
      run: cmake --build build_linux_64 --config Distribution --verbose --parallel

    # Linux artifact 
    - name: package_linux
      run: |
        mkdir -p bin/linux-x64/native
        mv build_linux_64/lib/libjoltc.so bin/linux-x64/native/libjoltc.so
    - uses: actions/upload-artifact@v3
      with:
        name: libs_linux
        path: bin

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.28

    - name: Configure osx-universal
      run: cmake -S "." -B "build_osx" -G Ninja -DCMAKE_BUILD_TYPE=Distribution
    - name: Build osx-universal
      run: cmake --build build_osx --config Distribution --verbose --parallel

    # macOS artifacts
    - name: package_osx
      run: |
        mkdir -p bin/osx-universal/native
        mv build_osx/lib/libjoltc.dylib bin/osx-universal/native/libjoltc.dylib
    - uses: actions/upload-artifact@v3
      with:
        name: libs_osx
        path: bin

  update_libs:
    name: Update Native Libs
    runs-on: windows-latest
    needs: [windows, linux, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Download windows lib
        uses: actions/download-artifact@v3
        with:
          name: libs_windows
          path: src/JoltPhysicsSharp/runtimes
      - name: Download ubuntu lib
        uses: actions/download-artifact@v3
        with:
          name: libs_linux
          path: src/JoltPhysicsSharp/runtimes
      - name: Download macos lib
        uses: actions/download-artifact@v3
        with:
          name: libs_osx
          path: src/JoltPhysicsSharp/runtimes
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: src/JoltPhysicsSharp/runtimes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: Updated native libs
          committer_name: GitHub Actions
          committer_email: actions@github.com